/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Docusaurus automatically builds the sidebar from the docs/ folder
  // structure + the _category_.json files generated by generate-docs.js.
  // Nothing to maintain here manually.
  notesSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
